# SPDX-License-Identifier: GPL-2.0

# conexant.c includes private HDA headers from sound/hda/common.
ccflags-y += -I$(src)/common

obj-m += snd-hda-codec-conexant.o
snd-hda-codec-conexant-y := conexant.o

