# SPDX-License-Identifier: GPL-2.0-or-later
PACKAGE_NAME="sn6140"
PACKAGE_VERSION="@VERSION@"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^[0-9].*-zen$"
BUILD_EXCLUSIVE_ARCH="^x86_64$"
BUILD_EXCLUSIVE_CONFIG="CONFIG_SND_HDA_CODEC_CONEXANT"
# Quoting bash prevents DKMS appending make-specific KERNELRELEASE/-j options.
MAKE[0]="'bash' scripts/dkms-build.sh ${kernelver}"
BUILT_MODULE_NAME[0]="snd-hda-codec-conexant"
DEST_MODULE_LOCATION[0]="/kernel/sound/hda/codecs"
PRE_INSTALL="scripts/dkms-pre-install.sh ${kernelver}"
